Step 2
blohin27/yandexBurger pull request #1
Opened 2023-02-06 20:25 UTC by blohin27

2023-02-06 20:46 UTC, andryxxa93 requested changes
Проделана большая работа! Вы хорошо разобрались с функциональными компонентами и правильно используете useEffect.

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Необходимо добавить проверку успешности запроса
- Элементы хедера должны быть ссылками а не просто текстом. Сделайте пока что через тег `<a/>`
- Убрать у `modalOverlay` `children`

Более подробно описание проблемы смотрите комментарии в pull request.

Что понравилось:
- На старте использовали `typescript`.
- Использовали кастомный `хук`.
- Используете `useMemo` и `useCallback`.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2023-02-06 20:46 UTC, andryxxa93 commented on src/components/App/App.tsx
> +    const data = await fetch(INGREDIENTS_URL);
**Надо исправить**
Добавьте проверку ответа сервера - res.ok:

Например:

```
.then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
```

иначе сейчас, если сервер ответи не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение

[https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)

[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

`fetch(someUrl).then(checkReponse)`

2023-02-06 20:46 UTC, andryxxa93 commented on src/components/App/App.tsx
> +      >
**Можно лучше**
Конкретные модальные окна лучше вынести в компоненты к которым они относятся. В `BurgerIngredient ` и `BurgerConstructor`. `App` это композиционный компонент, которому нет необходимости знать что-то про модальные окна с заказом или ингредиентом.

2023-02-06 20:46 UTC, andryxxa93 commented on src/types/types.ts
> +  arraySauce: IIngredient[],
**Можно лучше**
Необходимости в `arrayMain` и `arraySauce` нет, достаточно какой-то одной сущности. А вот булки отдельно выделить это хорошая идея.

2023-02-06 20:46 UTC, andryxxa93 commented on src/components/Modal/Modal.tsx
> +    <ModalOverlay onClick={onClose}>
**Надо исправить**

у ModalOverlay не должно быть children, это просто компонент подложки а не контейнер

2023-02-07 07:32 UTC, blohin27 commented on src/components/App/App.tsx
> +    const data = await fetch(INGREDIENTS_URL);
Исправил

2023-02-07 07:33 UTC, blohin27 commented on src/components/Modal/Modal.tsx
> +    <ModalOverlay onClick={onClose}>
Исправил

2023-02-07 11:51 UTC, andryxxa93 approved these changes
Супер! Все критические замечания исправлены, вы отлично поработали. Работа принята.
Желаю удачного продолжения обучения!

2023-02-07 11:57 UTC, merged